version: '3'
services:
    gatherme-authentication-ms:
        container_name: gatherme-authentication-ms
        build: .
        restart: always
        ports:
            - '3001:3001'
        links: 
            - gatherme-authentication-db
    gatherme-authentication-db:
        container_name: gatherme-authentication-db
        image: mongo
        ports: 
            - '27017:27017'


